[package]
name = "cel"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "cel"
path = "src/cel.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.44.0"
gl_loader = "0.1.2"
glm = "0.2.3"
gl = "0.14.0"
lazy_static = "1.4.0"